package com.Erandopi.Erando;

import com.codename1.components.SpanLabel;
import com.codename1.io.CharArrayReader;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
//import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
//import com.codename1.io.Log;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.messaging.Message;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.util.UIBuilder;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    private Button mailbtn;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        UIBuilder uib = new UIBuilder();

        Container ctn1 = uib.createContainer(theme, "GUI 1");
        Container ctn2 = uib.createContainer(theme, "GUI 2");
        //Container ctn3 = uib.createContainer(theme, "GUI 4");
        

        Form f1 = ctn1.getComponentForm();
        Form f2 = ctn2.getComponentForm();
        //Form f3 = ctn3.getComponentForm();

        Command cmd1 = new Command("Ajouter Avis ");
        Command cmd2 = new Command("Mes Temoignages");
        Command cmd3 = new Command("Update");
         Command cmd4 = new Command("ajouter un article");
         Command cmd5 = new Command("mes  articles");
        //Command cmdBack = new Command("Back");

        f1.getToolbar().addCommandToSideMenu(cmd1);
        f1.getToolbar().addCommandToSideMenu(cmd2);

        f2.getToolbar().addCommandToSideMenu(cmd2);
        f2.getToolbar().addCommandToSideMenu(cmd1);
        f1.getToolbar().addCommandToSideMenu(cmd4);
        f1.getToolbar().addCommandToSideMenu(cmd5);
        f2.getToolbar().addCommandToSideMenu(cmd4);
        f1.addCommandListener(e -> {

            if (e.getCommand() == cmd2) {
                affichertemoignange aff = new affichertemoignange(theme);
             aff.getF().show();
          

            } else if (e.getCommand() == cmd1) {
                 ajouterTemoiganage aj = new ajouterTemoiganage(theme);
            aj.getF().show();
            } else if (e.getCommand() == cmd4) {
             
                ajouterpublication p = new ajouterpublication(theme);
                p.getF().show();
            }else if (e.getCommand() == cmd5) {
             MesPublication p = new MesPublication(theme);
             p.getF().show();
            }

        });
//        f2.addCommandListener(e->{
//        
//            if(e.getCommand() == cmdBack)
//            {
//                f1.showBack();
//            }
//            
//        });
        

        f1.show();

    }


    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
