package com.mycompany.myapp;


import com.codename1.components.ImageViewer;
import com.codename1.components.MultiButton;
import com.codename1.components.SpanLabel;
import com.codename1.io.CharArrayReader;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.ui.Button;
import com.codename1.ui.ComboBox;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.list.GenericListCellRenderer;
import com.codename1.ui.util.UIBuilder;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

//import java.sql.Date;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {
       
    
    
    private Form current;
    private Resources theme;
     Form hi;
       

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        listrando l = new  listrando(theme);
         Command c1 = new Command("Créer un randonnee");
        Command c2 = new Command("Gérer Randonnee");
        //Command c3 =new Command("liste_reservation");
    
        l.getF().getToolbar().addCommandToSideMenu(c1);
         l.getF().getToolbar().addCommandToSideMenu(c2);
         //l.getF().getToolbar().addCommandToSideMenu(c3);
    
            l.getF().addCommandListener(e->{
            if(e.getCommand()==c1){
                addRando s = new addRando(theme);
                
                   
            }
            if(e.getCommand()==c2){
                listrando list = new listrando(theme);
                
                list.getF().show();
                   
            }
            
            });
        
        
//    listrando l = new listrando(theme);
//    l.getF().show();
//listrando l = new  listrando(theme);
l.getF().show();
    }
    private Map<String, Object> createListEntry(String name, String date) {
   //Map<String, Object> entry = new HashMap<>();
   Map< String,Object> entry = new HashMap<>();
   entry.put("Line1", name);
    entry.put("Line2", date);
    return entry;
    }
          
       
 
    
    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
       
        
    }}
    
    public void destroy() {
    }

}
    
   

         


